apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: my-account-image
        ports:
        - containerPort: 8082